services:
  my-app-front-prod:
    image: my-app-front-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:80
    container_name: my-app-front-prod
  my-app-back-prod: # The name of the service, can be anything
    image: my-app-back-prod # Declares which image to use
    build:
      context: ./backend # Declares where to build if image is not found
      dockerfile: Dockerfile
    ports: # Declares the ports to publish
      - 3001:3001
    volumes:
      - ./backend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    environment:
      MONGODB_URI: mongodb+srv://username:password123.@cluster0.5v2up.mongodb.net/?retryWrites=true&w=majority
      PORT: 3001
    container_name: my-app-back-prod
  nginx:
    image: nginx:1.20.1
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    depends_on:
      - my-app-front-prod
      - my-app-back-prod
