version: "3.8" # Version 3.8 is quite new and should work

services:
  app: # The name of the service, can be anything
    image: todo-backend # Declares which image to use
    build:
      context: . # Declares where to build if image is not found
      dockerfile: dev.Dockerfile
    ports: # Declares the ports to publish
      - 4000:4000
    environment:
      - REDIS_URL=redis://localhost:6379
      - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database
    container_name: todo-backend-app
